image: Visual Studio 2019

platform:
  - x64
  - Win32

install:
  - cinst llvm
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init.exe -y --default-host %TARGET%
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -V
  - cargo -V

build: false

test_script:
  - cargo test --verbose
  - cargo test --verbose --release